w = linspace(-pi,pi,512); 
num = [0.8 3 -0.2 0.1]; 
den = [1 0.1 -0.4 0.7]; 
h = freqz(num,den,w); 
subplot(211),plot(w/pi,abs(h)); 
xlabel('\omega/\pi'); 
ylabel('Bien do'); 
title('Pho bien do |X(e^{j\omega})|'); 
subplot(212),plot(w/pi,angle(h)); 
xlabel('\omega/\pi'); 
ylabel('Pha [rad]'); 
title('Pho pha arg(X(e^{j\omega}))'); 